name: 28556 Deploy na DockerHub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Docker build & push
    runs-on: self-hosted

    steps:
      - name: Kloniraj repozitorij
        uses: actions/checkout@v3

      - name: Preveri ali obstaja napaka.txt
        run: |
          if [ -f napaka.txt ]; then
            echo "Deploy ustavljen – testi niso uspešno zaključeni."
            cat napaka.txt
            exit 1
          fi

      - name: Prijava v DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Zgradi Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/alg-dn1:latest .

      - name: Potisni image na DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/alg-dn1:latest