name: 28556 Testiranje naloge

on:
  push:
    branches:
      - main

jobs:
  preveri-teste:
    name: Preveri obstoj testne skripte
    runs-on: self-hosted
    outputs:
      napaka_obstaja: ${{ steps.preveri.outputs.napaka_obstaja }}
    steps:
      - name: Kloniraj repozitorij
        uses: actions/checkout@v3

      - name: Preveri testno datoteko
        id: preveri
        run: |
          if [ ! -f "test_radix_sort.cpp" ]; then
            echo "Testna datoteka ne obstaja!" > napaka.txt
            echo "napaka_obstaja=true" >> $GITHUB_OUTPUT
          else
            echo "napaka_obstaja=false" >> $GITHUB_OUTPUT
          fi

      - name: Shrani napako kot artefakt (훾e obstaja)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: napaka
          path: napaka.txt
          if-no-files-found: ignore

  pozeni-teste:
    name: Po탑eni teste (훾e ni napake)
    needs: preveri-teste
    if: needs.preveri-teste.outputs.napaka_obstaja == 'false'
    runs-on: self-hosted

    strategy:
      matrix:
        compiler: [g++, clang++]

    steps:
      - name: Kloniraj repozitorij
        uses: actions/checkout@v3

      - name: Namesti build orodja
        run: sudo apt update && sudo apt install -y build-essential clang

      - name: Prevedi test z ${{ matrix.compiler }}
        run: ${{ matrix.compiler }} test_radix_sort.cpp main.cpp -o test_exec

      - name: Za탑eni test
        run: ./test_exec
